config/routes.rb
Rails.application.routes.draw do
resources :groups
 resources :concerts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'groups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
    belongs_to :group

    # def self.last_concerts(g)

    # where(group_id: g.id, event_date: Time.now.beginning_of_month..Time.now.end_of_month).order(event_date: :desc)         
    # end
    scope :last_concerts, -> (group) { where(group_id: group.id, event_date: Time.now.beginning_of_month..Time.now.end_of_month).order(event_date: :desc)}
    
    scope :max_audience, -> (group) { where(group_id: group.id).order(audience: :desc).includes(:group)}

    scope :max_time, -> (group) { where(group_id: group.id).order(duration: :desc).includes(:group)}
    
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :concerts, dependent: :destroy
    
    def total_concerts
        self.concerts.count
    end
    

    enum team: [:hombres, :mujeres, :banda]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
    render json: Concert.all
  end

  def new
    @concert = Concert.new
    @groups = Group.all
  end

  def show
    # byebug
    # render json: params
  end

  def create
    # byebug
    @concert = Concert.new(concert_params)
    @concert.save 
    redirect_to root_path
  end

  def edit
    @concert = Concert.find(params[:id])
    @groups = Group.all
  end

  def update
    @concert = Concert.find(params[:id])
    @concert.update(concert_params)
    redirect_to root_path
  end

  def destroy
  end

  private
  def concert_params
    params.require(:concert).permit(:name, :duration, :audience, :event_date, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @last_con = Concert.last_concerts(@group)
    @max_audie = Concert.max_audience(@group)
    @max_t = Concert.max_time(@group)

  end

  def new
  end

  def creates
    
  end

  def edit
  end

  def update
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to group_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/concerts/_form.html.erb
<%= form_with(model: concert, local: true) do |f|%>
    <div>
        <%= f.label 'Nombre' %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label 'Duracion' %>
        <%= f.time_field :duration, value: '%H:%M' %>
    </div>
    <div>
        <%= f.label 'Asistentes' %>
        <%= f.number_field :audience, min:0 %>
    </div>
    <div>
        <%= f.label 'Fecha' %>
        <%= f.date_field :event_date %>
    </div>
    <div>
        <%= f.label 'Nombre del grupo' %>
        <%= f.select :group_id, options_from_collection_for_select(@groups, :id, :name), prompt: 'Elige el grupo que tocara en el concierto' %>
    </div>
    
    <%= f.submit %>
<% end %>

app/views/concerts/edit.html.erb
<h1>Aqui puedes editar un concierto</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Atras', root_path %>

app/views/concerts/index.html.erb
<h1>Concerts#index</h1>
<p>Find me in app/views/concerts/index.html.erb</p>

app/views/concerts/new.html.erb
<h1>Agrega un concierto</h1>


<%= render 'form', concert: @concert %>

<%= link_to 'Atras', root_path %>

app/views/concerts/show.html.erb
<h1>Concerts#show</h1>
<p>Find me in app/views/concerts/show.html.erb</p>

app/views/groups/edit.html.erb
<h1>Groups#edit</h1>
<p>Find me in app/views/groups/edit.html.erb</p>

app/views/groups/index.html.erb
<h1>Informacion de los Grupos de nuestra Productora</h1>


<table> 
    <thead>
    <th> Accion</th>
    <th> Nombre grupo</th>
    <th> Cant. integrantes</th>
    <th> Fecha debut</th>
    <th> Team</th>
    <th> Cant. conciertos</th>
    <th> Info concierto</th>
    </thead>    

    <tbody>
    <% @groups.each do |group| %>
        <tr>
        <td>
            <%= link_to 'Ver', group %>
            <%= link_to 'Borrar', group, method: :delete, data:{confirm:'Estas seguro de querer borrarlo?',} %>
        </td>
        <td><%= group.name %></td>
        <td><%= group.members %></td>
        <td><%= group.debut %></td>
        <td><%= group.team %></td>
        <td><%= group.total_concerts %></td>
        <td>
            <% group.concerts.each do |concert| %>
            <li><%=" #{concert.name}, espectadores : #{concert.audience}"%></li>
           
            <% end %>
        </td>
        </tr>

        <% end %>
    </tbody>

</table>

<%= link_to 'crear concierto', new_concert_path %>

app/views/groups/new.html.erb
<h1>Groups#new</h1>
<p>Find me in app/views/groups/new.html.erb</p>

app/views/groups/show.html.erb
<h1>Groups#show</h1>

<table>
    <thead>
        <th>Nombre</th>
        <th>Cant. conciertos</th>
        <th>Fecha ultimo concierto</th>
        <th>Nombre ult. concierto</th>
    </thead>
    <tbody>
        <td><%= @group.name %></td>
        <td><%= @last_con.count %></td>
        <td><%= @last_con[0].event_date.strftime('%Y-%B-%A') %></td>
        <td><%= @last_con[0].name %></td>
    </tbody>
</table>
<table>
    <thead>
        <th>Audiencia maxima</th>
        <th>Nombre del concierto</th>

    </thead>
    <tbody>
        <td><%= @max_audie[0].audience  %></td>
        <td><%= @max_audie[0].name  %></td>
    </tbody>
</table>

<table>
    <thead>
        <th>Mayor tiempo de duracion</th>
        <th>Nombre del concierto</th>

    </thead>
    <tbody>
        <td><%= @max_t[0].duration.strftime('%H:%M') %> </td>
        <td><%= @max_t[0].name %></td>
      
    </tbody>
</table>
<%= link_to 'atras', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Productora</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>